channels:
- conda-forge
dependencies:
- python=3.8.5
- pip
- pip:
  - mlflow
  - cloudpickle==1.6.0
  - dataclasses==0.6
  - psutil==5.8.0
  - scikit-learn==0.24.2
  - typing-extensions==3.7.4.3
name: mlflow-env
